import {
  getArticleList,
  createArticle,
  updateArticle,
  searchArticle,
  getArticleDetail,
  releaseComment,
  getCommentList,
  giveLike,
  deleteComment,
  deleteArticle,
  likeArticle,
  getClassifyList,
  getTagList,
  getTimelineList,
  getArticleByRandom,
} from './article';
import { uploadFile } from './upload';
import { getMyArticleList, getAuthorArticleList } from './userInfo';
import { register, login, updateInfo, getUserInfo, updatePassword } from './user';

export {
  register,
  login,
  updateInfo,
  getUserInfo,
  getArticleList,
  createArticle,
  updateArticle,
  searchArticle,
  getArticleDetail,
  releaseComment,
  getCommentList,
  giveLike,
  deleteComment,
  deleteArticle,
  likeArticle,
  getClassifyList,
  getTagList,
  getTimelineList,
  getMyArticleList,
  uploadFile,
  updatePassword,
  getArticleByRandom,
  getAuthorArticleList,
};
