import {
  getArticleList,
  createArticle,
  updateArticle,
  searchArticle,
  articleDraft,
  getArticleDetail,
  getDraftList,
  getDraftById,
  deleteDraft,
  releaseComment,
  getCommentList,
  giveLike,
  deleteComment,
  deleteArticle,
  likeArticle,
  getClassifyList,
  getTagList,
  getTimelineList,
  getArticleByRandom,
  delAllArticle,
  getPrevArticle,
  getNextArticle,
  advancedSearch,
} from './article';
import { uploadFile } from './upload';
import { getMyArticleList, getAuthorArticleList, getAuthorTimeline } from './userInfo';
import {
  register,
  login,
  updateInfo,
  getUserInfo,
  updatePassword,
  resetPassword,
  verify,
} from './user';
import {
  createCollection,
  getCollectionList,
  collectArticles,
  checkCollectionStatus,
  cancelCollected,
  getCollectedTotal,
  delCollection,
  updateCollection,
  getCollectInfo,
  getCollectArticles,
  removeCollectArticle,
} from './collection';

export {
  register,
  login,
  updateInfo,
  getUserInfo,
  getArticleList,
  createArticle,
  updateArticle,
  searchArticle,
  articleDraft,
  getDraftList,
  getDraftById,
  deleteDraft,
  delAllArticle,
  getArticleDetail,
  releaseComment,
  getCommentList,
  giveLike,
  deleteComment,
  deleteArticle,
  likeArticle,
  getClassifyList,
  getTagList,
  getTimelineList,
  getMyArticleList,
  uploadFile,
  updatePassword,
  resetPassword,
  getArticleByRandom,
  getAuthorArticleList,
  getAuthorTimeline,
  getPrevArticle,
  getNextArticle,
  verify,
  advancedSearch,
  createCollection,
  getCollectionList,
  collectArticles,
  checkCollectionStatus,
  cancelCollected,
  getCollectedTotal,
  delCollection,
  updateCollection,
  getCollectInfo,
  getCollectArticles,
  removeCollectArticle,
};
