import {
  getArticleList,
  createArticle,
  updateArticle,
  searchArticle,
  articleDraft,
  getArticleDetail,
  getDraftList,
  releaseComment,
  getCommentList,
  giveLike,
  deleteComment,
  deleteArticle,
  likeArticle,
  getClassifyList,
  getTagList,
  getTimelineList,
  getArticleByRandom,
  delAllArticle,
  getPrevArticle,
  getNextArticle,
} from './article';
import { uploadFile } from './upload';
import { getMyArticleList, getAuthorArticleList, getAuthorTimeline } from './userInfo';
import { register, login, updateInfo, getUserInfo, updatePassword, verify } from './user';

export {
  register,
  login,
  updateInfo,
  getUserInfo,
  getArticleList,
  createArticle,
  updateArticle,
  searchArticle,
  articleDraft,
  getDraftList,
  delAllArticle,
  getArticleDetail,
  releaseComment,
  getCommentList,
  giveLike,
  deleteComment,
  deleteArticle,
  likeArticle,
  getClassifyList,
  getTagList,
  getTimelineList,
  getMyArticleList,
  uploadFile,
  updatePassword,
  getArticleByRandom,
  getAuthorArticleList,
  getAuthorTimeline,
  getPrevArticle,
  getNextArticle,
  verify,
};
